### ISSUE TITLE
Searching (BFS/Dijkstra/A*) with multiple starting nodes

### ISSUE THREAD

**Issue by danielhuang** [evenfurther/pathfinding#461]
Advent of Code [2022 day 12 part 2](https://adventofcode.com/2022/day/12) can be solved with multiple starting nodes. This can be currently accomplished by searching in reverse (starting from the end), but would be ideal if multiple starting nodes could be used directly.

Additionally, this could help with the case where there were multiple starting nodes as well as multiple ending nodes, which wouldn't be possible currently.

**Comment by samueltardieu** [comment]
I don't want to add things unless there is a real need for it. Your example is not very compelling, because as you wrote starting from the end is enough. Adding complicated code just in case it is useful for a problem some day adds to the maintenance burden.

If you can come us with code and a real test case which cannot be easily solved with the existing tools, then let us talk.

**Comment by stepancheg** [comment]
I have the same feature request (unrelated to AoC).

Use case if hard to explain without going into details on my project.

**Comment by danielhuang** [comment]
My code [here](https://github.com/danielhuang/aoc-2023/blob/master/src/bin/17.rs) uses multiple starting nodes
