### ISSUE TITLE
feat: ColIterator

### ISSUE THREAD

**Issue by mirsella** [evenfurther/pathfinding#493]
hello !

would be very useful to have a iterator on the columns, like row iter.

thanks !

**Comment by samueltardieu** [comment]
Having a column iterator is more involved than having a row iterator. While it is easy to return a row as a `&[T]` because values for one row are stored consecutively in memory, this is not the case for columns. A column iterator would either return items of type:

- a `Vec<T>`, by cloning values
- a `Vec<&T>`, by referencing values (but that would necessitate building the `Vec` anyhow)
- a `impl Iterator<&T>`, which makes it not really simpler than creating the iteration by hand

If you want to evaluate such an approach and submit a patch, please do.

**Comment by mirsella** [comment]
to try to be as close to the slice returned by rowiter, returning a vec<&c> would be the best no ?

the `grid` crate actually return a iterator<item = C> (each cell) in a iterator (each columns or row)

**Comment by samueltardieu** [comment]
> to try to be as close to the slice returned by rowiter, returning a vec<&c> would be the best no ?

It depends: if you intend to clone the values to make something with the column, `Vec<C>` would be the best as you could use it as-is. If you want to iterate over it, `Vec<&C>` would make sense.

Actually, it we wanted to add an `column_iter_mut()` as well, which would iterator over values of `Vec<&mut C>`, `Vec<&C>` would indeed make more sense.

**Comment by samueltardieu** [comment]
I have a prototype in #495. Would that do what you were expecting?

**Comment by mirsella** [comment]
Well done ! This is the optimal solution.

just realized, there is now matrix.iter_mut even for rows, or I didn't find it ? would be great to have one for row and columns as well !

**Comment by samueltardieu** [comment]
I can see a use for `.column_iter()` in one of my AoC problem, but so far I don't have a need for `.iter_mut()` for rows or columns. If you can demonstrate a use and provide a pull-request, please do so in another issue (and with the PR).

**Comment by samueltardieu** [comment]
`.column_iter()` is part of pathfinding 4.8.0 which has just been released
