### ISSUE TITLE
[Question] possible to maintain state while using the pathfinder

### ISSUE THREAD

**Issue by FloWi** [evenfurther/pathfinding#585]
Hi!

I'm currently trying to understand if and how I can use the crate for my scenario.

My goal is to find a path for a vehicle that consumes fuel, can refuel at certain nodes and has different modes of transportation (they affect speed and fuel-consumption) that it can switch at the nodes.

For illustration I created this small example

Specs
```text
start         fuel_station         goal 
(0,0)         (100, 0)             (200, 0)

fuel: 200
fuel_capacity: 600

duration_normal: 1.0 * distance  
duration_fast:   0.5 * distance

fuel_consumption_normal: 1.0 * distance
fuel_consumption_fast:   2.0 * distance
```

quickest path:
```text
- move to fuel_station in normal_mode (distance: 100; duration: 100s; fuel_consumption: 100l)
- refuel (2s)
- move to goal in fast_mode (distance: 100; duration: 50s; fuel_consumption: 200l)

-------------------------------------------------------

Duration: 152s
Fuel Consumption: 300l
```

slower path:
```text

- move to goal in normal_mode (distance: 200; duration: 200s; fuel_consumption: 200l)

-------------------------------------------------------

Duration: 200s
Fuel Consumption: 200l
```

I'd appreciate if someone could put me on the right path ;-)

**Comment by samueltardieu** [comment]
You must think of a pathfinding algorithm as an algorithm to find a path across a see of states. Finding a path across a 2D or 3D grid is just a specific case, in which the state is only made of a geographical position.

In your case, the state could be something like

- the geographical position,
- and the remaining amount of fuel

When determining the neighbours (each neighbour being a new state), you must determine:

- the geographical position of the new state,
- and the remaining amount of fuel when you have reached this new state — it must be non-negative, or this neighbour should not be considered

as well as the cost, which in your case would be the duration since it looks like this is the metrics that want to minimize.

For example, your starting node would be:

- position: (0, 0), fuel: 200L

It has two neighbours:

- position: (100, 0), remaining fuel: 100L – cost: 100s
- position: (100, 0), remaining fuel: 0L – cost: 50s

If I only consider the first neighbour here, it itself has several neighbours:

- position: (0, 0), remaining fuel: 0L – cost: 100s (back to the starting point but with no fuel left)
- position: (100, 0), remaining fuel: 600L – cost: 2s (refuel)
- position: (200, 0), remaining fuel: 0L – cost 100s

Note that for if fuel is allowed to be 0 when reaching a node, the fastest path is start→fuel station→goal. I guess this is not the case given your example, so you can remove the neighbours for which the remaining fuel is 0L (the second one in each of my examples).

I hope this is clear enough.

**Comment by FloWi** [comment]
Hi @samueltardieu! 

Thanks for taking the time to write such a helpful response! Appreciate it!

Your examples made it very clear on how to think about the problem. 

And you even found a bug in my example, since it _is_ ok to arrive at a node with 0 fuel. I'll experiment with it soon and will let you know if I got it to run. 

I'll close the issue for now, so it's not distracting.

**Comment by FloWi** [comment]
> I'll experiment with it soon and will let you know if I got it to run.

Works like a charm! 

Starting with 200 fuel:

```text
Path found with cost 102:
Travel Actions:
0. Starting at start (fuel: 200)
1. Navigate from start to fuel_station (distance: 100.00, travel time: 50, fuel consumption: 200, mode: Fast, total time: 50)
2. Refuel at fuel_station (total time: 52)
3. Navigate from fuel_station to goal (distance: 100.00, travel time: 50, fuel consumption: 200, mode: Fast, total time: 102)

```

Starting with 100 fuel:

```text
Path found with cost 152:
Travel Actions:
0. Starting at start (fuel: 100)
1. Navigate from start to fuel_station (distance: 100.00, travel time: 100, fuel consumption: 100, mode: Normal, total time: 100)
2. Refuel at fuel_station (total time: 102)
3. Navigate from fuel_station to goal (distance: 100.00, travel time: 50, fuel consumption: 200, mode: Fast, total time: 152)
```
